name: 'banvic_dw'
version: '1.0.0'
config-version: 2
profile: 'banvic_dw'

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]

models:
  banvic_dw:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts

on-run-end:
  - "{{ populate_test_results() }}"
