name: 'analytics_poc'
version: '1.0.0'
config-version: 2
profile: 'analytics'

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]

models:
  analytics_poc:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts

on-run-end:
  - "{{ populate_test_results() }}"
