apiVersion: v1
kind: ConfigMap
metadata:
  name: dw-init-scripts
  namespace: banvic
data:
  01_create_databases.sql: |
    CREATE DATABASE analytics_dw;
    CREATE DATABASE metabase_app;

  02_create_schemas.sql: |
    \c analytics_dw;
    CREATE SCHEMA IF NOT EXISTS raw;
    CREATE SCHEMA IF NOT EXISTS staging;
    CREATE SCHEMA IF NOT EXISTS marts;

  03_create_metadata_schema.sql: |
    \c analytics_dw;
    CREATE SCHEMA IF NOT EXISTS metadata;

    CREATE TABLE IF NOT EXISTS metadata.test_results (
        test_name       TEXT,
        model_name      TEXT,
        column_name     TEXT,
        status          TEXT,
        message         TEXT,
        executed_at     TIMESTAMP WITH TIME ZONE DEFAULT NOW()
    );

    CREATE TABLE IF NOT EXISTS metadata.model_runs (
        model_name       TEXT,
        materialization  TEXT,
        schema_name      TEXT,
        row_count        BIGINT,
        status           TEXT,
        message          TEXT,
        executed_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW()
    );
