apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: airflow-db
  namespace: banvic
spec:
  selector:
    matchLabels:
      app: airflow-db
  serviceName: airflow-db
  replicas: 1
  template:
    metadata:
      labels:
        app: airflow-db
    spec:
      containers:
      - name: postgres
        image: postgres:16
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: banvic-secrets
              key: AIRFLOW_DB_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: banvic-secrets
              key: AIRFLOW_DB_PASSWORD
        - name: POSTGRES_DB
          value: airflow
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
        readinessProbe:
          exec:
            command: ["pg_isready", "-U", "airflow", "-d", "airflow"]
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: airflow-db
  namespace: banvic
spec:
  selector:
    app: airflow-db
  ports:
  - port: 5432
    targetPort: 5432
  publishNotReadyAddresses: true
