apiVersion: apps/v1
kind: Deployment
metadata:
  name: metabase
  namespace: banvic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metabase
  template:
    metadata:
      labels:
        app: metabase
    spec:
      containers:
      - name: metabase
        image: metabase/metabase:v0.50.31
        ports:
        - containerPort: 3000
        env:
        - name: MB_DB_TYPE
          value: postgres
        - name: MB_DB_HOST
          value: dw-postgres
        - name: MB_DB_PORT
          value: "5432"
        - name: MB_DB_DBNAME
          value: metabase_app
        - name: MB_DB_USER
          valueFrom:
            secretKeyRef:
              name: banvic-secrets
              key: DW_POSTGRES_USER
        - name: MB_DB_PASS
          valueFrom:
            secretKeyRef:
              name: banvic-secrets
              key: DW_POSTGRES_PASSWORD
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: metabase
  namespace: banvic
spec:
  type: NodePort
  selector:
    app: metabase
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30300
